### ISSUE TITLE
Feature request: enable proxy contract detection via Etherscan API

### ISSUE THREAD

**Issue by yohamta** [shazow/whatsabi#125]
The [Etherscan getsource API](https://docs.etherscan.io/api-endpoints/contracts#get-contract-source-code-for-verified-contract-source-codes) includes a proxy flag and the address of the implementation in its response. By using this data, we can enhance the flexibility of proxy detection.

For instance, in the current release of Whatsabi, the implementation of the [USDCv3 Token](https://etherscan.io/address/0xc3d688b66703497daa19211eedff47f25384cdc3#code) does not seem to be retrieved. However, the Etherscan API response flags it as a proxy and provides the address of the implementation. By adding the `isProxy` and `implementation` fields to the `ContractResult` structure, we can enhance proxy detection and retrieve the correct implementation addresses.

### Proposal:

Modify the ContractResult type to include `isProxy` and `implementation` fields. Additionally, update the `EtherscanABILoader` to populate these fields from the Etherscan API response.

```diff
export type ContractResult = {
    abi: any[];
    name: string | null;
    evmVersion: string;
    compilerVersion: string;
    runs: number;

    ok: boolean; // False if no result is found

    /**
     * getSources returns the imports -> source code mapping for the contract, if available.
     *
     * Caveats:
     * - Not all loaders support this, so the property could be undefined.
     * - This call could trigger additional fetch requests, depending on the loader.
     **/
    getSources?: () => Promise<ContractSources>;

    userdoc?: any;
    devdoc?: any;

+    isProxy?: boolean;
+    implementation?: string;
}
```

We are willing to submit a pull request to implement this feature if that would be acceptable.

**Comment by shazow** [comment]
> For instance, in the current release of Whatsabi, the implementation of the [USDCv3 Token](https://etherscan.io/address/0xc3d688b66703497daa19211eedff47f25384cdc3#code) does not seem to be retrieved.

HMM, I think this is a bug, we can fix it. Opened an issue here: https://github.com/shazow/whatsabi/issues/126

> However, the Etherscan API response flags it as a proxy and provides the address of the implementation. By adding the isProxy and implementation fields to the ContractResult structure, we can enhance proxy detection and retrieve the correct implementation addresses.

I'm not opposed to adding these, but I'm hesitant to add a bunch of fields that are specific to a single loader source (including userdoc, devdoc). I was hoping that `ContractResult` would contain normalized results so that the user doesn't need to worry where it came from.

So let's step back for a moment and consider some alternatives instead of inlining `{ userdoc, devdoc, isProxy, implementation }`:

1. We could include a `rawResponse: any` object which just includes the underlying response. That way if anything is missing and you know which source it came from, you can always dig through it?
2. We could turn `ContractSource` into an interface, and use polymorphic results: Etherscan would return an `EtherscanContractResult` which implements `ContractSource` but additionally contain `isProxy` and `implementation. We would do something similar with `SourcifyContractResult` to include `userdoc` and `devdoc`.
3. We could do embedding (like rawResponse) but only for a specific subset of non-normalized functionality, so something like `ContractResult.extra = { "sourcify": { userdoc, devdoc }, "etherscan": { isProxy, implementation }}`. This would be more explicit about what's coming from where.

I lean towards 3.

What do you think?

**Comment by yohamta** [comment]
@shazow Thank you for the thorough response! I understand the concern about maintaining a normalized structure for ContractResult. I agree that adding fields specific to a single source could complicate things. Your third suggestion, embedding the extra data in a dedicated field, seems like a good compromise. I’m happy to go with that approach.

That said, having a `rawResponse` would also be helpful. It would allow users to handle potential future issues (e.g., missing field values) with more flexibility on their side.

Would you like us to move forward with a pull request based on this idea?

**Comment by shazow** [comment]
@yohamta I can make that change. :)

I'm happy to add `rawResponse`, my only argument against it is that it would be easier to get feedback from consumers of which fields they need. I worry if we add `rawResponse`, I'll never hear from anyone. 😅

Not a great reason, though.

I'm hesitant to add both `rawResponse` _and_ `extra`. What do you think? Should I just do `rawResponse`?

**Comment by shazow** [comment]
@yohamta Sounds like a plan. I'll do that and will ping you with a PR when it's ready. :)

**Comment by shazow** [comment]
Opened PR here: https://github.com/shazow/whatsabi/pull/127

Also added a test which contains your example:

https://github.com/shazow/whatsabi/blob/d6b179d11ad15bec2438374e1237be7f2fc8f0b5/src/__tests__/loaders.test.ts#L118-L124
