### ISSUE TITLE
loaders: Add anyabi.xyz

### ISSUE THREAD

**Issue by shazow** [shazow/whatsabi#90]
https://anyabi.xyz/

It's redundant with etherscan and sourcify, but could make it race or a fallback?

**Comment by k-thornton** [comment]
I had some code using AnyABI which I thought would easily slot in here.  The problem is that AnyABI is missing [a lot of the details ](https://anyabi.xyz/api/get-abi/1/0x32400084C286CF3E17e7B677ea9583e60a000324)that you'd expect from getContract.  To add AnyABI, you would need to add the Optional ? to `evmVersion`, `compilerVersion`, and `runs`

export type ContractResult = {
    abi: any[];
    name: string | null;
    ok: boolean;
    evmVersion**?**: string;
    compilerVersion**?**: string;
    runs**?**: number;
    getSources?: () => Promise<ContractSources>;
    loader?: ABILoader;
    loaderResult?: EtherscanContractResult | SourcifyContractMetadata | any;
}

gut feel, is it worth it?

**Comment by shazow** [comment]
I'm down if you are. :) Could also add a `AnyABIContractResult` for including the full result in `loaderResult` .

**Comment by shazow** [comment]
Also looks like they mainly return the `loadABI` equivalent which is fine. Makes sense for `ContractResult` to basically be a superset if available, otherwise roughly equivalent.

I'm down to change the type as you mentioned.

**Comment by shazow** [comment]
Fixed via #163
